import { ScoreItem } from "@/src/component/RecorderDashboardUI";

export const allScores: Record<number, ScoreItem[]> = {
    1: [
      {
        id: 1,
        archer: "John Doe",
        bow_type: "Recurve",
        tournament_id: 1,
        tournament_name: "National Archery Cup",
        submitted_at: "2025-11-10T13:45:00Z",
        total_score: 290,
        status: "pending",
        details: [
          { round: 1, range: "70m", shots: [9, 10, 8, 9, 10, 9] },
          { round: 2, range: "70m", shots: [9, 9, 10, 8, 9, 10] },
        ],
      },
      {
        id: 2,
        archer: "Jane Smith",
        bow_type: "Compound",
        tournament_id: 1,
        tournament_name: "National Archery Cup",
        submitted_at: "2025-11-10T14:10:00Z",
        total_score: 278,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [8, 9, 10, 9, 8, 9] },
          { round: 2, range: "50m", shots: [9, 8, 9, 9, 10, 8] },
        ],
      },
      {
        id: 3,
        archer: "Alex Johnson",
        bow_type: "Recurve",
        tournament_id: 1,
        tournament_name: "National Archery Cup",
        submitted_at: "2025-11-10T15:05:00Z",
        total_score: 305,
        status: "approved",
        details: [
          { round: 1, range: "70m", shots: [10, 10, 9, 10, 10, 9] },
          { round: 2, range: "70m", shots: [10, 9, 10, 10, 9, 10] },
        ],
      },
    ],

    2: [
      {
        id: 4,
        archer: "Maria Garcia",
        bow_type: "Compound",
        tournament_id: 2,
        tournament_name: "City Invitational",
        submitted_at: "2025-11-11T10:00:00Z",
        total_score: 267,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [8, 9, 8, 9, 8, 9] },
          { round: 2, range: "50m", shots: [9, 8, 9, 8, 9, 8] },
        ],
      },
      {
        id: 5,
        archer: "Li Wei",
        bow_type: "Recurve",
        tournament_id: 2,
        tournament_name: "City Invitational",
        submitted_at: "2025-11-11T10:22:00Z",
        total_score: 312,
        status: "approved",
        details: [
          { round: 1, range: "70m", shots: [10, 10, 9, 10, 10, 10] },
          { round: 2, range: "70m", shots: [10, 9, 10, 10, 10, 10] },
        ],
      },
      {
        id: 6,
        archer: "Noah Brown",
        bow_type: "Barebow",
        tournament_id: 2,
        tournament_name: "City Invitational",
        submitted_at: "2025-11-11T11:01:00Z",
        total_score: 251,
        status: "pending",
        details: [
          { round: 1, range: "30m", shots: [8, 7, 8, 8, 7, 8] },
          { round: 2, range: "30m", shots: [7, 8, 7, 8, 8, 7] },
        ],
      },
    ],

    3: [
      {
        id: 7,
        archer: "Emily Davis",
        bow_type: "Recurve",
        tournament_id: 3,
        tournament_name: "International Shoot",
        submitted_at: "2025-11-07T09:30:00Z",
        total_score: 298,
        status: "approved",
        details: [
          { round: 1, range: "70m", shots: [9, 10, 9, 10, 9, 9] },
          { round: 2, range: "70m", shots: [9, 10, 9, 10, 9, 9] },
        ],
      },
      {
        id: 8,
        archer: "Oliver Martinez",
        bow_type: "Compound",
        tournament_id: 3,
        tournament_name: "International Shoot",
        submitted_at: "2025-11-07T10:15:00Z",
        total_score: 283,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [9, 8, 9, 9, 9, 8] },
          { round: 2, range: "50m", shots: [8, 9, 9, 8, 9, 9] },
        ],
      },
      {
        id: 9,
        archer: "Sophia Wilson",
        bow_type: "Barebow",
        tournament_id: 3,
        tournament_name: "International Shoot",
        submitted_at: "2025-11-07T11:45:00Z",
        total_score: 275,
        status: "pending",
        details: [
          { round: 1, range: "30m", shots: [9, 8, 9, 8, 9, 8] },
          { round: 2, range: "30m", shots: [8, 9, 8, 9, 8, 9] },
        ],
      },
    ],

    4: [
      {
        id: 10,
        archer: "Ethan Clark",
        bow_type: "Recurve",
        tournament_id: 4,
        tournament_name: "Regional Open",
        submitted_at: "2025-11-09T09:12:00Z",
        total_score: 299,
        status: "approved",
        details: [
          { round: 1, range: "70m", shots: [10, 10, 9, 10, 10, 9] },
          { round: 2, range: "70m", shots: [9, 10, 9, 10, 9, 10] },
        ],
      },
      {
        id: 11,
        archer: "Ava Lewis",
        bow_type: "Compound",
        tournament_id: 4,
        tournament_name: "Regional Open",
        submitted_at: "2025-11-09T09:40:00Z",
        total_score: 264,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [8, 9, 8, 8, 9, 8] },
          { round: 2, range: "50m", shots: [8, 8, 9, 8, 8, 9] },
        ],
      },
      {
        id: 12,
        archer: "Mason Walker",
        bow_type: "Recurve",
        tournament_id: 4,
        tournament_name: "Regional Open",
        submitted_at: "2025-11-09T10:18:00Z",
        total_score: 307,
        status: "approved",
        details: [
          { round: 1, range: "70m", shots: [10, 10, 10, 9, 10, 10] },
          { round: 2, range: "70m", shots: [10, 9, 10, 10, 10, 9] },
        ],
      },
    ],

    5: [
      {
        id: 13,
        archer: "Isabella Hall",
        bow_type: "Recurve",
        tournament_id: 5,
        tournament_name: "Winter Challenge",
        submitted_at: "2025-11-08T13:20:00Z",
        total_score: 288,
        status: "pending",
        details: [
          { round: 1, range: "70m", shots: [9, 9, 10, 9, 9, 9] },
          { round: 2, range: "70m", shots: [9, 9, 9, 9, 9, 9] },
        ],
      },
      {
        id: 14,
        archer: "Lucas Allen",
        bow_type: "Compound",
        tournament_id: 5,
        tournament_name: "Winter Challenge",
        submitted_at: "2025-11-08T14:05:00Z",
        total_score: 270,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [9, 8, 8, 9, 8, 8] },
          { round: 2, range: "50m", shots: [8, 8, 9, 8, 8, 9] },
        ],
      },
      {
        id: 15,
        archer: "Mia Young",
        bow_type: "Barebow",
        tournament_id: 5,
        tournament_name: "Winter Challenge",
        submitted_at: "2025-11-08T14:40:00Z",
        total_score: 320,
        status: "approved",
        details: [
          { round: 1, range: "30m", shots: [10, 10, 10, 10, 10, 10] },
          { round: 2, range: "30m", shots: [10, 10, 10, 10, 10, 10] },
        ],
      },
      {
        id: 16,
        archer: "Logan Hernandez",
        bow_type: "Compound",
        tournament_id: 5,
        tournament_name: "Winter Challenge",
        submitted_at: "2025-11-08T15:12:00Z",
        total_score: 255,
        status: "pending",
        details: [
          { round: 1, range: "50m", shots: [8, 7, 8, 8, 7, 8] },
          { round: 2, range: "50m", shots: [7, 8, 7, 8, 7, 8] },
        ],
      },
    ],
}